#CONFIGURAÇÔES

SCREEN_WIDTH  = 400
SCREEN_HEIGHT = 750

PERIQUITO_WIDTH  = 45
PERIQUITO_HEIGHT = PERIQUITO_WIDTH * (13/18)
PERIQUITO_SIZE = (PERIQUITO_WIDTH,PERIQUITO_HEIGHT)
INTENSIDADEPULO = 12

CANO_WIDTH  = 90
CANO_HEIGHT = 600
CANO_GAP_INCIAL = 180
CANO_TAMNHOMINIMO = 30
cano_gap    =  CANO_GAP_INCIAL

CHAO_ALTURA = 100

VELOCIDADE_JOGO = 0
VELOCIDADE_YLIMITE = 7
GRAVIDADEIDEAL = 0.5
GRAVIDADE = 0

pontuacao = 0